import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ConvexClientProvider from './ConvexClientProvider'
import Link from 'next/link'
import { ClerkProvider, useAuth } from "@clerk/clerk-react";
import { ConvexProviderWithClerk } from "convex/react-clerk";
import { ConvexReactClient } from "convex/react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Fitness',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='grid grid-cols-2'>
          <div className='w-80'>

            <nav >
              <Link href="/">Dashboard</Link>
              <Link href="/Macros">Macros</Link>
              <Link href="/Mass">Mass</Link>
              <Link href="/Habits">Habits</Link>
            </nav>
          </div>
          <div className='col-span-1'>

            <ConvexClientProvider>{children}</ConvexClientProvider>
          </div>
        </div>
      </body>
    </html>
  )
}
